server:
  port: 9003
spring:
  application:
    name: board-service
  datasource:
    url: jdbc:mysql://192.168.0.47:3306/board2?serverTimezone=UTC&characterEncoding=UTF-8
    username: jeongho
    password: 1234

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
file: E:\MSA\test\Rollin-Msa-Board\src\main\resources\static